#!/bin/bash

LSI_SRC=AgiPalLSI

# Compile Java source
javac -verbose -cp "lib/*" ${LSI_SRC}.java

# Run Java class file
# NOTE: Prior to including classpath, we can't find our (import) packages,
# and when we include cp, we can't find or load main class AgiPalLSI
# TODO: Fix this or move to Windows
java -verbose -cp "lib/*" ${LSI_SRC}

# Remove excess
rm ${LSI_SRC}.class
